### PR TITLE
Setup Prettier

### PR DESCRIPTION
**Pull request by umangutkarsh**
This PR sets up prettier for the News-Aggregation-App.

Prettier Version: `3.3.0`

The following tasks have been completed:
- [X] Setup prettier
- [X] Format all files (except in `.prettierignore`)

### CODE REVIEW

**Comment by umangutkarsh** [comment]
Hi @abhinavkrin . These can be reviewed since these are independent of #6

**Comment by abhinavkrin** [comment]
Hey @umangutkarsh I think we should resolve the conflicts only after merging the other PRs and then merge this PR.

**Comment by umangutkarsh** [comment]
Yes ok

**Review by abhinavkrin — APPROVED** [review]

**Comment by umangutkarsh** [comment]
@abhinavkrin ready to merge!

**Pull request merged**
