### PR TITLE
Helper message with slash command - `/news help`

### PR DESCRIPTION
**Pull request by umangutkarsh**
This PR includes the following:

- [X] Command `/news help` implemented
- [X] Info message of various slash commands can be displayed

[screen-capture (2).webm](https://github.com/RocketChat/News-Aggregation-App/assets/95426993/18383d69-41f9-499f-9503-f344197b8ea3)

Files to review:
1. `commandEnum.ts`
2. `commandUtility.ts`
3. `message.ts`

### CODE REVIEW

**Comment by abhinavkrin** [comment]
@umangutkarsh  Please resolve the merge conflicts and rebase/merge the branch with develop.

**Comment by umangutkarsh** [comment]
> @umangutkarsh  Please resolve the merge conflicts and rebase/merge the branch with develop.

Will resolve asap

**Comment by umangutkarsh** [comment]
> @umangutkarsh Please resolve the merge conflicts and rebase/merge the branch with develop.

done!

**Comment by umangutkarsh** [comment]
Hi @abhinavkrin . Please review this once, (basic command setup done in this PR)

**Review by abhinavkrin — APPROVED** [review]
LGTM!

**Pull request merged**
