### PR TITLE
App Command Setup (Add slash command options)

### PR DESCRIPTION
**Pull request by umangutkarsh**
This PR adds all slash command options (more can be added) for the app.

### CODE REVIEW

**Comment by umangutkarsh** [comment]
Hi @abhinavkrin . This PR can be reviewed

**Review by abhinavkrin — APPROVED** [review]
LGTM!

**Comment by abhinavkrin** [comment]
Hey @umangutkarsh  Please resolve the conflicts and rebase with the develop branch.

**Comment by umangutkarsh** [comment]
@abhinavkrin done!

**Review by abhinavkrin — APPROVED** [review]

**Pull request merged**
